import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Link } from "@/components/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <nav className="mb-4 flex container mx-auto p-3">
          <ul className="flex gap-2">
            <li>
              <Link href="/">Main page</Link>
            </li>
            <li>
              <Link href="/meals">Meals</Link>
            </li>
          </ul>
        </nav>
        <main className="flex container mx-auto px-3">{children}</main>
        <footer className="flex container mx-auto px-3"></footer>
      </body>
    </html>
  );
}

